config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  get 'user_mailer/contact_form'

  get 'static_pages/thank_you'

  resources :products do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#landing_page'
  # root :to => "products#index"

  post 'static_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'

  resources :orders, only: [:index, :show, :create, :destroy]

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments

  validates :name, presence: true
  validates :description, presence: true
  # search for a word similar to user input
  # check if production or development env.
  def self.search(search_term)
    if Rails.env == 'production'
      Product.where("name ilike ?", "%#{search_term}%")
    else
      Product.where("name LIKE ?", "%#{search_term}%")
    end
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_asc.first
  end

  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    # byebug
    # return filtered products
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
      if @products.blank?
        flash[:alert] = 'There are no results that match your search'
      end
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
              <% if signed_in? && current_user.admin? %>
                <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-text-field' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-textarea' %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url, class: 'form-text-field' %>
  </div>

  <div class="field">
  <%= f.label :colour %>
  <%= f.text_field :colour, class: 'form-text-field' %>
  </div>

  <div class="field">
  <%= f.label :price %>
  <%= f.text_field :price, class: 'form-text-field' %>
  </div>

  <div class="actions form-button">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body, class: 'form-control', id:'exampleTextarea', rows:'3' %>
    </p>
    <p>
      <div class="rating"></div>
    </p>
    <p>
      <%= f.submit "Submit", class:'btn btn-primary' %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-xs-12 col-sm-6 col-md-3">
  <div class="display-product">
  <% cache product do %>
    <% if product.image_url.present? %>
      <%= link_to  image_tag(product.image_url, class: "img-responsive product-img"), product %>
    <% end %>
    <div class="product-description">
      <p class="product-name"><%= product.name %></p>
      <p>Description: <%= product.description %></p>
      <p>Colour: <%= product.colour %></p>
    </div>
    <hr class="divider">
    <p class="product-price">Price: <%= product.price %> &euro;</p>

    <div class="product-links">
      <span><%= link_to 'Show', product %></span>
      <% if current_user && current_user.admin? %>
        <span><%= link_to 'Edit', edit_product_path(product) %></span>
        <span><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } %></span>
      <% end %>
    <% end %>
    </div>
  </div>
</div> <!-- /col -->

app/views/products/edit.html.erb
  <header>
    <h1>Editing Product</h1>
  </header>
  <div class="row">
    <div id="product-form">
      <%= render 'form', product: @product %>
    </div>
  </div>
  <div class="product-links">
    <%= link_to 'Show', @product %> |
    <%= link_to 'Back', products_path %>
  </div>

app/views/products/index.html.erb
<% if signed_in? && current_user.admin? %>
  <div class="create-product">
    <%= link_to 'Create New Product', new_product_path %>
  </div>
<% end %>
<header>
  <h1>Shop</h1>
</header>
<div class="row">
<% cache(cache_key_for_products) do %>
  <% @products.each do |product| %>
    <%= render partial: "product", locals: {product: product} %>
  <% end %>
<% end %>
</div>

app/views/products/new.html.erb
<header>
  <h1>New Product</h1>
</header>
<div class="row">
  <div id="product-form">
    <%= render 'form', product: @product %>
  </div>
</div>
<div class="product-links">
  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row" data-product-id="<%= @product.id %>">
    <div class="col-xs-12 col-sm-6 col-md-6 show-product-img">
    <!-- <% cache @product do %> -->
      <% if @product.image_url.present? %>
        <%= image_tag(@product.image_url, data_zoom_image: "@product.image_url", class: "img-zoom img-responsive product-img") %>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4 description">
      <p>
        <strong>Name:</strong>
        <%= @product.name %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>

      <p>
        <strong>Colour:</strong>
        <%= @product.colour %>
      </p>

      <p class="show-product-price">
        <strong>Price:</strong>
        <%= @product.price %> &euro;
      </p>
      <p>Average Rating: <span class="rated" id="average-rating" data-score="<%= @product.average_rating %>"></span> </p>
      <p>
        Highest Rating:
        <span class="rated" id="highest-rating" data-score="<%= @product.highest_rating_comment.try(:rating) %>"></span>
        </br>
        <strong>Comment:</strong> <%= @product.highest_rating_comment.try(:body) %>
      </p>
      <div>
        <%= form_tag "/payments/create" do %>
          <%= render partial: "shared/stripe_checkout_button" %>
        <% end %>
      </div>
    </br>
      <div class="show-product-link">
        <%= link_to ' Back', products_path, class: 'glyphicon glyphicon-arrow-left btn btn-primary', role: 'button'%>
        <% if signed_in? && current_user.admin? %>
        <%= link_to ' Edit', edit_product_path(@product), class: 'glyphicon glyphicon-edit btn btn-primary', role: 'button' %>
        <% end %>
    <!-- <% end %> -->
      </div>
    </div>
  </div>
</br>
  <div class="row">
    <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
    <% if signed_in? %>
    <div class="col-xs-12 col-sm-5 col-md-5 comments">
      <%= render partial: "new_comment", locals: {comment: @comment} %>
    </div>
    <div class="col-xs-0 col-sm-1 col-md-1 comments"></div>
    <% end %>
    <div class="col-xs-12 col-sm-6 col-md-6 comments">
      <%= render partial: "comments", locals: {comment: @comment} %>
      <div class="apple_pagination">
          <div class="apple_pagination page_entries">
            <%= page_entries_info @comments %>
          </div>
          <%= will_paginate @comments, :container => false %>
      </div>
    </div>
  </div>
</div>