config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  get 'user_mailer/contact_form'

  get 'static_pages/thank_you'

  resources :products do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#landing_page'
  # root :to => "products#index"

  post 'static_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'

  resources :orders, only: [:index, :show, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Best Bikes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/master/devicon.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-style">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button aria-expanded="false" class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Best Bikes', root_path, class: 'navbar-brand' %>
        </div><!-- Collect the nav links, forms, and other content for toggling -->

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right link-style">
            <li class="search-form field">
              <%= form_tag("/products", method: "get") do %>
                <!-- <%= label_tag(:q, "Search for:") %> -->
                <%= text_field_tag(:q, nil, :placeholder => 'Search for a product', class: 'search-field') %>
                <%= submit_tag("Search", class: 'search-button') %>
              <% end %>
            </li>
            <li>
              <%= link_to 'Home', root_path %>
            </li>
            <li>
              <%= link_to 'Shop', products_path %>
            </li>
            <li>
              <%= link_to 'About', static_pages_about_path %>
            </li>
            <li>
              <%= link_to 'Contact', static_pages_contact_path %>
            </li>

            <% if user_signed_in? %>
              <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
              <li>
                <div class="btn-group">
                  <button type="button" class="btn btn-user dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= link_to(current_user.first_name, users_path) %> <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li><%= link_to('Orders', orders_path) %></li>
                    <li><%= link_to('Profile', users_path) %></li>
                    <li><%= link_to('Change Passowrd', edit_user_registration_path) %></li>
                  </ul>
                </div>
              </li>
            <% else %>
             <li>
               <%= link_to('Login/Sign up', new_user_session_path) %>
             </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="page-wrap">

      <div class="container-fluid">
        <% if notice %>
          <div class="alert alert-success" role="alert"><%= notice %></div>
       <% elsif alert %>
         <div class="alert alert-danger" role="alert"><%= alert %></div>
       <% end %>

        <%= yield %>

      </div>

    <div class="push"></div>
    </div>

    <footer class="site-footer">
      <p>&copy; 2017 Best Bikes</p>
    <footer>

  </body>
</html>